In [3]:
import pandas as pd

data = pd.read_csv('dataset/서울특별시 보육통계 연도별 어린이집 및 아동현황 정보.csv',index_col=False,encoding='euc-kr')
data2 = pd.read_csv('dataset/서울특별시 보육통계 연도별 영유아 인구수 및 보육현황 정보.csv',index_col=False,encoding='euc-kr')
data3 = pd.read_excel('dataset/서울어린이집데이터.xlsx',index_col=False)
data4 = pd.read_csv('dataset/보건복지부_평가인증_어린이집_현황.csv',index_col='연번',encoding='euc-kr')
data5 = pd.read_csv('dataset/서울특별시 보육통계 어린이집 정원현원 충족률 현황(자치구,유형별)정보.csv',index_col=False,encoding='euc-kr')
data6 = pd.read_csv('dataset/국공립 이용률.csv',index_col=False,encoding='euc-kr')
data['교사당 아동 수'] = data['아동현원']  / data['교직원수']
data3 = data3.drop('Unnamed: 0',axis=1)
data3['Child_EM'] = round(data3['CHILD_CNT_TOT'] / data3['EM_CNT_A2'],2)
data6.head()

  자치구명      2014      2015      2016      2017      2018      2019      2020
0   강남  0.405338  0.410006  0.405715  0.410650  0.428770  0.465927  0.491100
1   강동  0.185611  0.204946  0.242841  0.272781  0.308959  0.352615  0.398250
2   강북  0.186028  0.201167  0.230750  0.279764  0.310331  0.363476  0.392005
3   강서  0.190920  0.211169  0.223340  0.246053  0.253610  0.283993  0.352796
4   관악  0.263587  0.294393  0.304183  0.359503  0.387576  0.447481  0.508147

In [73]:
with open('dataset/어린이_교통사고_발생률.txt','r')as f:
    data = f.read()

d1 = data.replace('\n','\t').split('\t')
da1 = d1[9:18]

da2 = d1[18:]
year = da2[0::9]
year = pd.Series(year)
local = da2[1::9]
local = pd.Series(local)
child_a_val = da2[2::9]
child_a_val = pd.Series(child_a_val)
child_d_val = da2[3::9]
child_d_val = pd.Series(child_d_val)
child_i_val = da2[4::9]
child_i_val = pd.Series(child_i_val)
area_child_a = da2[5::9]
area_child_a = pd.Series(area_child_a)
area_child_i = da2[6::9]
area_child_i = pd.Series(area_child_i)
walk_child_d = da2[7::9]
walk_child_d = pd.Series(area_child_d)
walk_child_i = da2[8::9]
walk_child_i = pd.Series(walk_child_i)

col = pd.Series(da1)
df = pd.DataFrame([year,local,child_a_val,child_d_val,child_i_val,area_child_a,area_child_i,walk_child_d,walk_child_i])
df = df.transpose()
df.rename(col,axis=1,inplace=True)

df.columns = ['기간','지역','어린이 교통사고 발생건수','어린이 교통사고 사망자수','어린이 교통사고 부상자수','보호구역내 어린이 사고 발생건수','보호구역내 어린이 사고 부상자수','어린이 보행 사망자수','어린이 보행 부상자수']
df
# df.to_csv('dataset/지역별 어린이 사고율.csv')
# 어린이 인구 대비 비율로 다시

,기간,지역,어린이 교통사고 발생건수,어린이 교통사고 사망자수,어린이 교통사고 부상자수,보호구역내 어린이 사고 발생건수,보호구역내 어린이 사고 부상자수,어린이 보행 사망자수,어린이 보행 부상자수
0,2020,합계,928,2,"1,078",65,70,70,276
1,2020,종로구,16,-,19,1,1,1,3
2,2020,중구,14,-,15,2,2,2,7
3,2020,용산구,24,-,28,2,2,2,8
4,2020,성동구,18,-,20,1,1,1,4
5,2020,광진구,22,-,25,4,4,4,12
6,2020,동대문구,31,-,33,4,4,4,8
7,2020,중랑구,62,-,70,1,1,1,9
8,2020,성북구,32,-,35,2,2,2,13
9,2020,강북구,33,-,43,1,1,1,8
10,2020,도봉구,19,-,20,2,2,2,9
11,2020,노원구,54,-,67,1,2,2,11
12,2020,은평구,36,-,42,1,1,1,12
13,2020,서대문구,36,1,42,2,3,3,13
14,2020,마포구,34,-,43,2,2,2,5
15,2020,양천구,47,1,49,4,4,4,13
16,2020,강서구,43,-,50,5,5,5,14
17,2020,구로구,32,-,39,4,5,5,16
18,2020,금천구,20,-,23,1,1,1,7
19,2020,영등포구,50,-,58,4,4,4,14
20,2020,동작구,24,-,29,2,2,2,6
21,2020,관악구,34,-,41,2,2,2,14
22,2020,서초구,43,-,50,3,3,3,9
23,2020,강남구,76,-,94,6,8,8,20
24,2020,송파구,88,-,101,1,1,1,24
25,2020,강동구,40,-,42,7,7,7,17

In [1]:
with open('dataset/지역별_도시위험도.txt','r')as f:
    data = f.read()

d1 = data.replace('\n','\t').split('\t')
columns = d1[0:8]
year = d1[8::8]
da1 = d1[9::8]
# print(columns)
# da1

In [107]:
with open('dataset/교통안전지수.txt') as f :
    data = f.read()

data = data.replace('\n','\t').split('\t')
col = data[0:3]
year = data[3::3]
local = data[4::3]
safe_val = data[5::3]

year = pd.Series(year)
local = pd.Series(local)
safe_val = pd.Series(safe_val)

df = pd.DataFrame([year,local,safe_val],index=col).transpose()
df.to_csv('dataset/서울 지역별 교통안전지수.csv')

In [15]:
import pandas as pd
with open('dataset/서울시 보육시설 통계.txt') as f:
    data = f.read()

data = data.replace('\n','\t').split('\t')
columns = data[:11]
year = data[11::11]
gu = data[12::11]
dong = data[13::11]
tot = data[14::11]
gukgong = data[15::11]
beupin = data[16::11]
danchae = data[17::11]
mingan = data[18::11]
gajung = data[19::11]
bumo = data[20::11]
jikjang = data[21::11]
da = pd.DataFrame([year,gu,dong,tot,gukgong,beupin,danchae,mingan,gajung,bumo,jikjang],index=columns).transpose()
da.to_csv('dataset/서울시 보육시설 통계.csv')

In [16]:
import pandas as pd
with open('dataset/서울시 보육시설 통계.txt') as f:
    file = f.readlines()
line= []
for i in file:
    line.append(i.replace('\n','\t').strip().split('\t'))
import numpy as np
df = pd.DataFrame(line)
df.replace({'-':np.nan},inplace=True)

In [23]:
import pandas as pd
with open('dataset/서울시 보육시설 이용 통계.txt') as f:
    file = f.readlines()
line= []
for i in file:
    line.append(i.replace('\n','\t').strip().split('\t'))
import numpy as np
df = pd.DataFrame(line)
df.replace({'-':np.nan},inplace=True)
df.to_csv('dataset/서울시 보육시설 이용 통계.csv')

In [46]:
import pandas as pd
seoul = pd.read_csv('dataset/서울시 지역 정보.csv',index_col=False,encoding='euc-kr')
seoul.rename(columns={'EMD_CD':'행정지역코드','EMD_NM':'동'},inplace=True)
seoul.drop(['SGG_OID','COL_ADM_SE','GID'],axis=1,inplace=True)

In [261]:
import folium
import json

la = 37.566374677531904
lo = 126.9781670442717
map = folium.Map([la,lo],zoom_start=10,tiles='Stamen Toner')

df = pd.read_csv('dataset/서울시 보육시설 통계.csv')
df.기간 = df.기간.astype(int)
df.dtypes
df.drop(['Unnamed: 0'],axis=1,inplace=True)
data1 = 'dataset/서울시 지역 정보.geojson'
data2 = json.load(open(data1))

folium.Choropleth(geo_data=data2,data=df,columns=('동','합계'),key_on='features.properties.name',fill_color='BuPu').add_to(map)

map

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [260]:
df.기간 = df.기간.astype(object)
df.dtypes

기간         object
자치구        object
동          object
합계         object
국공립        object
사회복지법인     object
법인·단체 등    object
민간         object
가정         object
부모협동       object
직장         object
dtype: object

In [201]:
da = pd.read_csv('dataset/서울시_보육시설_이용.csv')
da.drop('Unnamed: 0',axis=1,inplace=True)
#pd.merge(da,seoul,on=['동'])
df

,기간,자치구,동,계_정원,국공립_정원,민간_정원,가정_정원,계_현원,국공립_현원,민간_현원,가정_현원,기타_정원,기타_현원,행정지역코드,동
0,2020.0,합계,합계,245863.0,101037.0,82308.0,33972.0,196260.0,85925.0,62749.0,27106.0,28546.0,20480.0,11440124,연남동
1,2020.0,종로구,소계,4700.0,2216.0,344.0,50.0,3263.0,1615.0,254.0,39.0,2090.0,1355.0,11440121,동교동
2,2020.0,종로구,사직동,727.0,101.0,58.0,0.0,570.0,80.0,50.0,0.0,568.0,440.0,11290104,동소문동1가
3,2020.0,종로구,삼청동,55.0,32.0,0.0,0.0,39.0,23.0,0.0,0.0,23.0,16.0,11290123,안암동3가
4,2020.0,종로구,부암동,154.0,131.0,0.0,0.0,125.0,113.0,0.0,0.0,23.0,12.0,11590103,상도1동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11740110,강일동
464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11740102,고덕동
465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11740103,상일동
466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11440108,대흥동
467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11440110,노고산동

In [257]:
da1 = pd.read_csv('dataset/서울시_주민등록인구.csv',index_col=0,thousands = ',' )
da2 = pd.read_csv('dataset/서울시_보육시설_이용.csv',index_col=0)
da3 = pd.read_csv('dataset/서울시_보육시설.csv',index_col=0)
da4 = pd.read_csv('dataset/형법범죄율_2019.csv',index_col=0,encoding='euc-kr')
da5 = pd.read_csv('dataset/교통안전지수 시군구.csv',index_col=0)
da6 = pd.read_csv('dataset/서울시 공원 (1인당 공원면적) 통계.csv',index_col=0,encoding='euc-kr')
da7 = pd.read_csv('dataset/서울시 출생사망(동별) 통계.csv',index_col=0,encoding='euc-kr')
da8 = pd.read_csv('dataset/서울시_주택.csv',index_col=0,thousands=',')
da9 = pd.read_csv('dataset/서울시_종사자밀도.csv',index_col=0)
da10 = pd.read_csv('dataset/서울시_종사자수.csv',index_col=0)

da8.replace('X',np.nan,inplace=True)
da_obj = da8[['자치구','동']]
da_int = da8.drop(['자치구','동'],axis=1)

In [274]:
data = pd.read_csv('dataset/서울시 우리마을가게 상권분석서비스.csv',encoding='euc-kr')
df = data[['기준 년 코드','기준_분기_코드','월_평균_소득_금액','소득_구간_코드','상권_코드_명','상권_코드']]
df

       기준 년 코드  기준_분기_코드  월_평균_소득_금액  소득_구간_코드   상권_코드_명    상권_코드
0         2021         1     2850735         6   풍성로37가길  1001010
1         2021         1     3146942         7      천호옛길  1001009
2         2021         1     2774214         6    천호옛14길  1001008
3         2021         1     2561943         6  천호대로219길  1001007
4         2021         1     3001401         7  천호대로197길  1001006
...        ...       ...         ...       ...       ...      ...
28275     2014         2     4808322         8      백석동길  1000005
28276     2014         2     3451327         7       명륜길  1000004
28277     2014         2     3412262         7  돈화문로11가길  1000003
28278     2014         2     3959710         8    난계로27길  1000002
28279     2014         2     3994609         8       계동길  1000001

[28280 rows x 6 columns]